In [2]:
import urllib.request
import os
import sqlite3
import pandas as pd

In [ ]:
url_chinook = "https://raw.githubusercontent.com/lerocha/chinook-database/master/ChinookDatabase/DataSources/Chinook_Sqlite.sqlite"
ruta_db     = "chinook.db"

if not os.path.exists(ruta_db):
    urllib.request.urlretrieve(url_chinook, ruta_db)
    print(f"Base de datos descargada en: {ruta_db}")
else:
    print(f"La base de datos ya existe: {ruta_db}")

La base de datos ya existe: chinook.db

NameError: name 'cur' is not defined

In [ ]:
con = sqlite3.connect("chinook.db")
cur = con.cursor()

1. ¿Cuántas pistas hay en total en la base de datos?

In [ ]:

resultado = pd.read_sql_query("SELECT COUNT(TrackId) from Track", con)

print(f"Pistas totales: {resultado}")

Pistas totales:    COUNT(TrackId)
0            3503

2. ¿Cuántos géneros distintos existen?

In [ ]:
resultado = pd.read_sql_query("SELECT DISTINCT COUNT(GenreID) from Genre", con)
print(f"Generos distantos: {resultado}")

Generos distantos:    COUNT(GenreID)
0              25

3. Obtén el nombre del género, el número de pistas y la duración promedio (en minutos) para cada género. Ordena de mayor a menor número de pistas.

In [ ]:
resultado = pd.read_sql_query("""
  SELECT
   DISTINCT g.name AS "genre",
   COUNT(t.TrackID) AS "total_tracks",
   AVG(t.Milliseconds / 60000) AS "duration"
  FROM Track t
  JOIN Genre g ON g.GenreID=t.GenreID
  GROUP BY g.name
  ORDER BY total_tracks DESC""", con)

resultado.head(5)

                genre  total_tracks  duration
0                Rock          1297  4.222051
1               Latin           579  3.390328
2               Metal           374  4.668449
3  Alternative & Punk           332  3.412651
4                Jazz           130  4.400000

4. ¿Cuáles son las 5 pistas más largas? Muestra el nombre, el álbum y la duración en minutos.

In [ ]:
resultado = pd.read_sql_query("""
SELECT t.name, t.Milliseconds, a.Title
FROM Track t
JOIN Album a ON a.AlbumID=t.AlbumID
ORDER BY
Milliseconds DESC
LIMIT 5""", con)

resultado.head(10)

,Name,Milliseconds,Title
0,Occupation / Precipice,5286953,"Battlestar Galactica, Season 3"
1,Through a Looking Glass,5088838,"Lost, Season 3"
2,"Greetings from Earth, Pt. 1",2960293,"Battlestar Galactica (Classic), Season 1"
3,The Man With Nine Lives,2956998,"Battlestar Galactica (Classic), Season 1"
4,"Battlestar Galactica, Pt. 2",2956081,"Battlestar Galactica (Classic), Season 1"

¿Cuántas pistas tienen un UnitPrice superior a $0.99? ¿Qué porcentaje representan del total?

In [ ]:
resultado = pd.read_sql_query("""
SELECT
COUNT(TrackID) AS totales,
COUNT(TrackID) * 100 / (SELECT COUNT(TrackID) FROM Track) percentaje
FROM Track
WHERE UnitPrice > 0.99
""", con)

resultado.head(10)

   totales  percentaje
0      213           6

Calcula la media, mínimo, máximo y varianza (en SQL) de la duración en milisegundos de todas las pistas.

In [ ]:
resultado = pd.read_sql_query("""
SELECT
ROUND(AVG(Milliseconds) AS median,
MIN(Milliseconds) AS min,
MAX(Milliseconds) AS max,
ROUND(AVG(Milliseconds * Milliseconds) - AVG(Milliseconds)*AVG(Milliseconds), 2) AS varianza
FROM Track
""", con)


resultado.head(5)

      median   min      max      varianza
0  393599.21  1071  5286953  2.861491e+11

Ejercicio 2: Análisis descriptivo de ventas
Usando las tablas Invoice e InvoiceLine, responde:

¿Cuál es el total de ingresos generados por la tienda? ¿Y el promedio por factura?

In [ ]:
resultado = pd.read_sql_query("""
SELECT SUM(Total),
AVG(Total) AS Mean
FROM Invoice
""", con)


resultado.head(5)

   SUM(Total)      Mean
0      2328.6  5.651942

¿Cuántas facturas se emitieron por año? Ordena cronológicamente.

In [ ]:
resultado = pd.read_sql_query("""
SELECT strftime('%Y', InvoiceDate) AS Year,
COUNT(InvoiceID) AS Total
FROM Invoice
GROUP BY Year
ORDER BY Year
""", con)


resultado.head(5)

   Year  Total
0  2021     83
1  2022     83
2  2023     83
3  2024     83
4  2025     80

Identifica los 5 países con más ingresos. Muestra: país, número de facturas, ingreso total y promedio por factura.

In [ ]:
resultado = pd.read_sql_query("""
SELECT strftime('%Y', InvoiceDate) AS Year,
COUNT(InvoiceID) AS Total
FROM Invoice
GROUP BY Year
ORDER BY Year
""", con)


resultado.head(5)